<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Models\FI\General\**" />
		<Compile Remove="Reports\**" />
		<EmbeddedResource Remove="Models\FI\General\**" />
		<EmbeddedResource Remove="Reports\**" />
		<None Remove="Models\FI\General\**" />
		<None Remove="Reports\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
	</ItemGroup>
</Project>